version: '3'
services:
  metawear_ros:
    image: gabry993/metawear_ros:galactic
    network_mode: host
    privileged: true
    command: ros2 launch metawear_ros _main.launch
    volumes:
      - ./logs:/root/.ros/log:rw
      - ./_main.launch:/ros_ws/install/share/metawear_ros/launch/_main.launch:ro
      - ./profile.xml:/profile.xml
    environment:
      - "FASTRTPS_DEFAULT_PROFILES_FILE=/profile.xml"
      - "USER_NAME=$USER_NAME"
